<?php



/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
function oulib_bento_libraries_info() {

  /* Specify Mustache.js library, used for tempalting */

  $libraries['mustache.js'] = array(
    'name' => 'Mustache js templates',
    'vendor url' => 'https://mustache.github.io/',
    'download url' => 'https://mustache.github.io/',
    'version' => '2.3.0',
    'files' => array(
      'js' => array('mustache.js')
    )
  );

  return $libraries;

}


/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function oulib_bento_block_info(){

  $blocks = array();
  $blocks['oubento_search'] =  array(
    'info' => t('Bento - Search Form'),
  );
  $blocks['oubento_results_primo'] = array(
    'info' => t('Bento - Primo Search Results'),
  );
  $blocks['oubento_results_primobooks'] = array(
    'info' => t('Bento - Primo Books Search Results'),
  );

  $blocks['oubento_results_primoshareok'] = array(
    'info' => t('Bento - Primo SHAREOK Search Results'),
  );

  $blocks['oubento_results_libguides']  = array(
    'info' => t('Bento - Lib Guides  Search Results'),
  );

  return $blocks;
}

function oulib_bento_theme($existing, $type, $theme, $path) {
  return array(
    'oubento_search' => array(
      'template' => 'oubento_search',
      'variables' => array(),
    ),
    'oubento_results' => array(
      'template' => 'oubento_results',
      'variables' => array(),
    ),
  );
}


function oulib_bento_block_view($delta='') {


  libraries_load("mustache.js");

  $block = array();
  $variables = array();


  switch($delta) {
    case 'oubento_search' :
      $block['subject'] = t('Search');
      $block['content'] = theme('oubento_search', $variables);
      break;
    case 'oubento_results_primo' :
      $variables['silo'] = "primo";
      $block['subject'] = t('Primo Results');
      $block['content'] = theme('oubento_results', $variables);
      break;
    case 'oubento_results_primobooks' :
      $variables['silo'] = "primobooks";
      $block['subject'] = t('Primo Books Results');
      $block['content'] = theme('oubento_results', $variables);
      break;
    case 'oubento_results_primoshareok' :
      $variables['silo'] = "primoshareok";
      $block['subject'] = t('Primo SHAREOK Results');
      $block['content'] = theme('oubento_results', $variables);
      break;
    case 'oubento_results_libguides' :
      $variables['silo'] = "libguides";
      $block['subject'] = t('LibGuides Results');
      $block['content'] = theme('oubento_results', $variables);
      break;

  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function oulib_bento_menu(){

  /* proxy settings */
  $items['admin/config/search/bento']
    = array(
    'title' => 'One search settings',
    'description' => 'Configure the settings for One Search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oulib_bento_settings'),
    'access arguments' => array('administer suma_stats settings'),
  );

  return $items;
}

// uncomment this if we want permissions set on 1S settings
//function suma_stats_permission() {
//  $modperms = array(
//    'administer oulib_bento settings' => array(
//      'title' => t('Administer One Search Settings'),
//    ),
//  );
//  return $modperms;
//}

/**
 * @return mixed
 *
 * Configuration settings for the OneSearch
 */
function oulib_bento_settings() {

  $form = array();

  $form['oulib_bento_server'] = array(
    '#type' => 'textfield',
    '#title' => t('One Search URI'),
    '#default_value' => variable_get('oulib_bento_server', ""),
    '#description' => t("The URI for One Search"),
    '#required' => TRUE,
  );

  $form['oulib_bento_search_limit'] = array(
    '#type' => 'textfield',
    '#title' => t('Results Limit'),
    '#default_value' => variable_get('oulib_bento_search_limit', 5),
    '#description' => t('The number of results to display to the user'),
    '#required' => TRUE,
    '#size' => 3,
    '#maxlength' => 3,
  );

  return system_settings_form($form);
}

$serverURI = variable_get('oulib_bento_server', "");
$resultLimit = variable_get('oulib_bento_search_limit', 10);

drupal_add_js(array(
  'oulib_bento' => array(
    'searchURI' => $serverURI,
    'resultLimit' => $resultLimit)),
  array('type' => 'setting'));
